### ISSUE TITLE
Import error for sunpy.map in v6.1.1

### ISSUE THREAD

**Issue by sr-dash** [sunpy/sunpy#8109]
### Describe the bug

With a fresh installation of Miniconda and SunPy v6.1.1, the map import  with `import sunpy.map`, gives the following error,

```
from mpl_toolkits.axes_grid1.anchored_artists import AnchoredEllipse, AnchoredSizeBar
ImportError: cannot import name 'AnchoredEllipse' from 'mpl_toolkits.axes_grid1.anchored_artists' 
```

I am using MacOS. The installed version of dependent packages are,

`matplotlib == 3.10.0`
`numpy == 1.26.4`
`scipy == 1.15.1`
`python == 3.11.11`
`astropy == 6.1.3`

Is there a bug in the new release? 

Thanks in advance.

### To Reproduce

import sunpy.map

### System Details

OS: Mac OS 10.16
Arch: 64bit, (i386)
sunpy: 6.1.1

Required Dependencies
#####################
astropy: 6.1.3
fsspec: 2024.12.0
numpy: 1.26.4
packaging: 24.2
parfive: 2.1.0
pyerfa: 2.0.1.5
requests: 2.32.3

### Installation method

conda

**Comment by nabobalis** [comment]
When you say fresh install? Can you detail the steps you did?

I am just surprised a fresh install, installed an out of date version of astropy.

Can you also provide the full output log from the import error please?

My first reaction would be to update astropy to version 7 and see if that helps.

**Comment by ayshih** [comment]
`astropy` needs to be either 7.0.0+ or 6.1.5+ to work with `matplotlib` 3.10.x

**Comment by ayshih** [comment]
You indicated that you are using `miniconda` (i.e., rather than `miniforge`).  We do not recommend using `miniconda` (or `anaconda`) because it uses the `anaconda` "defaults" channel:

- The versions on "defaults" can lag behind, which may be why you installed an old version of `astropy`
- Depending on your situation, using "defaults" may not be free.  See https://sunpy.org/posts/2024/2024-08-09-anaconda/

**Comment by ayshih** [comment]
> * The versions on "defaults" can lag behind, which may be why you installed an old version of `astropy`

To illustrate, `astropy` 6.1.5 was released on November 7, and `astropy` 7.0.0 was released on November 22.  However, "defaults" continued to offer only `astropy` 6.1.3 as the latest until January 28.  "defaults" had `matplotlib` 3.10 available starting January 7, so I'm guessing that your fresh install took place between January 7 and January 28 (or you are working off of stale package indices).

**Comment by sr-dash** [comment]
I am so sorry for the late reply. I was creating a new env with dependencies where pandas was restricted for a lower version which resulted in the equivalent (/old) compatible version of astropy. After updating pandas and astropy the import map function is working now. Thanks for the suggestions and timely support.

**Comment by ayshih** [comment]
Thanks for following up!  I'll note that the problem is still presumably partially due to `anaconda` "defaults", because that channel is outright missing `astropy` 6.1.5, 6.1.6, or 6.1.7, each of which would probably satisfy that panda dependency while also being compatible with `matplotlib` 3.10.
