### ISSUE TITLE
astropy_helpers is not automatically being initialized by setup.py

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2932]
This could well be related to #2920 

---

With the latest `master` branch checked out, running `python setup.py make_docs` gives me

```
$ python setup.py build_docs
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from astropy_helpers.setup_helpers import setup, register_commands # noqa
ImportError: cannot import name 'setup' from 'astropy_helpers.setup_helpers' (/Users/dstansby/miniconda3/lib/python3.7/site-packages/astropy_helpers/setup_helpers.py)
```

I've checked that `astropy_helpers` is installed properly using `pip install astropy_helpers --upgrade`.

**Comment by nabobalis** [comment]
You might need to check that the submodule is pointing at master.

**Comment by dstansby** [comment]
Possibly caused by https://github.com/sunpy/sunpy/pull/2920, judging by the `setup.py` blame.

**Comment by dstansby** [comment]
Do I really have to have a submodule checked out to master in order to build (and therefore contribute to) the docs?

**Comment by nabobalis** [comment]
Right now (probably) yes. That PR made some changes to setup.py that require the upstream master of helpers. 

Cadair is working on planning to remove the submodule in the future. But more upstream work needs to occur.

**Comment by nabobalis** [comment]
In fact, I am not sure that anything works without the submodule. But I have never actually tried.

**Comment by dstansby** [comment]
Are there instructions on how to do that in the SunPy docs somewhere? (I can't find them). It seems slightly crazy to depend on the master branch of another project, and expect other people to be able to keep up with that.

**Comment by nabobalis** [comment]
Normally the submodule is checked out at a release version but it just happens to be set differently right now. When Astropy 3.2 comes out, we will update that.

The command should be in the developer documentation.

But the command should be `git submodule update --init`.

**Comment by dstansby** [comment]
👍 that worked a treat, thanks! Maybe worth adding a note to that effect to https://docs.sunpy.org/en/latest/dev_guide/documentation.html#usage ?

**Comment by nabobalis** [comment]
We should add it to more places, currently the message is only here: https://docs.sunpy.org/en/latest/dev_guide/newcomers.html#astropy-helpers

But I am in the process of redoing the entire dev docs.

**Comment by Cadair** [comment]
`setup.py` Should automatically checkout the submodule. I wonder if something is borked? @astrofrog you got any ideas why the auto-submodule stuff wouldn't be working?

**Comment by astrofrog** [comment]
I'm not sure, this is handled inside ``ah_bootstrap.py`` normally.

**Comment by nabobalis** [comment]
So I deinit-ed the submodule and ran `python setup.py test` 
and it did run `Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`` 

I also checked out the submodule to a different version from my current head and it did update it. It again corrected it if it was different.

**Comment by Cadair** [comment]
Ah right ok, so a fresh clone should work, but people will have to update themselves?

I am a bit confused as to why the changes we made to setup.py broke the auto-pull though, there is nothing in the setup.py which should prevent a proper import of `ah_bootstrap.py`? I don't know at what point the submodule update happens though.

**Comment by nabobalis** [comment]
I'd have to check but I recall it tries to import a function that doesn't exist.

**Comment by nabobalis** [comment]
So checking again:

I check out helpers to v3.0.2 and add it to the commit history:

`Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from astropy_helpers.setup_helpers import setup, register_commands # noqa
ImportError: cannot import name 'setup' from 'astropy_helpers.setup_helpers' (/home/nabil/Git/sunpy/astropy_helpers/astropy_helpers/setup_helpers.py)
`

Which is the same error as before.

**Comment by Cadair** [comment]
I think the solution is to run `git submodule sync` before `git submodule update --init` to fix this I think.
