### ISSUE TITLE
`test_retry_sample_data` test failing

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6320]
### Describe the bug

```python
____________________________ test_retry_sample_data ____________________________
[gw1] linux -- Python 3.9.13 /home/runner/work/sunpy/sunpy/.tox/py39-online/bin/python
tmpdir = local('/tmp/pytest-of-runner/pytest-0/popen-gw1/test_retry_sample_data2')
    @pytest.mark.remote_data
    def test_retry_sample_data(tmpdir):
        # Wrong base URL.
        result = _download_sample_data(
            "http://ipv4.download.thinkbroadband.com/", [("tca110607.fits",
                                                         tmpdir.strpath+"/tca110607.fits")], False)
        assert result == []
        assert result.errors != []
        # Inside _retry_sample_data, the base url will be updated to point towards
        # http://data.sunpy.org/sunpy/v1/
>       result_retry = _retry_sample_data(result)
E       TypeError: _retry_sample_data() missing 1 required positional argument: 'new_url_base'
```

I'm 99% sure this was broken by https://github.com/sunpy/sunpy/pull/6295

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by Cadair** [comment]
whoops

**Comment by nabobalis** [comment]
Should be a simple test fix.
